sudo: required

# Headless variable for Firefox
env:
  global:
    - MOZ_HEADLESS=1

# Use python with version 3.6
language: python
python:
  - 3.7

# Use Bionic Beaver 18.x
dist: bionic

# Add chrome and firefox browsers
addons:
  chrome: stable
  firefox: latest

# xvfb for virtual framebuffer --> webtestit requires graphical UI support
services:
  - xvfb

# make sure the proper python version is installed and pip updated
before_install:
  - if ! [ -f ./rxwt/webtestit ]; then
    wget --no-check-certificate  --force-directories -O rxwt/webtestit https://www.ranorex.com/wp-json/sage/v2/webtestit/app-download/?platform=linuxAppImage;
    fi
  - sudo apt-get install desktop-file-utils
  - sudo apt-get install python3-venv -y
  - sudo apt-get install openjdk-11-jdk -y
  - python --version
  - pip install -U pip
  - pip --version
  - java --version
  - javac --version
  - chmod a+x ./rxwt/webtestit

# install dependencies
install:
  - pip install -r ./requirements.txt


# run webtestit
script: ./rxwt/webtestit run .

cache:
  directories:
    - $TRAVIS_BUILD_DIR/rxwt/ 